### ISSUE TITLE
Missing defaults for duration_buckets

### ISSUE THREAD

**Issue by christopherraa** [tyldum/mojolicious-plugin-prometheus#4]
The documentation specifies that `duration_buckets` should have a default of `(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10)`. Such is not the case in the code.

Is the code or the doc at fault?

**Comment by tyldum** [comment]
Those are the defaults from Net::Prometheus in this case. I'm not sure it's best to document that instead or copypasta the defaults from Net::Prometheus. As it stands not it leaves room for errors, agreed.

**Comment by christopherraa** [comment]
Perhaps a note on that and where in Net::Prometheus those defaults can be found would be beneficial? Since their documentation does not hold those defaults the best thing might be to link directly to the line in code where it is defined.
