### ISSUE TITLE
Ambiguous wording in documentation

### ISSUE THREAD

**Issue by christopherraa** [tyldum/mojolicious-plugin-prometheus#5]
The documentation says **In addition to exporting the default ...**. Is it worth considering using **exposes** instead, since **exporting** has a special meaning in Perl?

**Comment by tyldum** [comment]
OTOH exporting is the correct terminology for Prometheus. I went over the same arguments in my head as I wrote it.

**Comment by christopherraa** [comment]
When I read the documentation my immediate reaction was *"why would he export stuff from this module?"* and then I went to look at the code. When I could not find traces of exporting I was left puzzled. Perhaps a short explaination could be helpful? Something along the lines of *"The use of 'exporting' here is not to be confused with exporting in Perl. This module does not export any Perl methods."*?
