### ISSUE TITLE
Possible bug in after_dispatch hook

### ISSUE THREAD

**Issue by christopherraa** [tyldum/mojolicious-plugin-prometheus#6]
The after_dispatch hook runs `$c->res->content->asset->size` when logging response size. However, if the response is HTTP multipart then `asset()` does not exist. It is only `Mojo::Content::Single` that has `->asset()`. The method `->is_multipart()` does however exist on `Mojo::Content` so checking for this is possible.

**Comment by tyldum** [comment]
Care to write a test? :)

**Comment by eforbus** [comment]
+1. This happens for me as well..

Can't locate object method "asset" via package "Mojo::Content::MultiPart" at /perls/perl-5.20.1/lib/site_perl/5.20.1/Mojolicious/Plugin/Prometheus.pm line 84.
